### ISSUE TITLE
Fehler auf der homeean-Webseite

### ISSUE THREAD

**Issue by hblaschka** [homeean/buildscripts#14]
Auf der Webseite https://homeean.de/buildscript sollte der Link hinter Wiki zu homeean auch dorthin führen (https://www.homeepedia.de/books/homeean/page/homeean---hintergrund-installation-und-nutzung) der Link hinter homee Community sollte auf https://community.hom.ee/t/homeean-skriptsammlung-fuer-webhook-apis-fuer-homee-und-einen-raspberry-pi/10166 führen.

Auf der Presence-Seite https://homeean.de/presence sollte IMO noch ein Link auf den Thread in der Community eingebaut werden (nicht jeder hat einen Github-Account):
https://community.hom.ee/t/anwesenheitserkennung-mit-homeean-presence/12744

**Comment by stfnhmplr** [comment]
Fixed.
