### ISSUE TITLE
Download of Buildscript not possible

### ISSUE THREAD

**Issue by moritzfl** [homeean/buildscripts#9]
I tried generating buildscripts with two different browsers (Chrome and Safari) on macOS. I tried a variaty of settings as well. However following the generation of the script (the button seems to trigger something after all), no download is started and no download button is available.

The screenshot of a sample configuration is attached to this comment. "Indivudelle Konfiguration" was deactivated.
![bildschirmfoto 2018-05-30 um 09 14 43](https://user-images.githubusercontent.com/18644803/40705093-39e39452-63ea-11e8-81af-0bdcc9f4e5af.png)

**Comment by stfnhmplr** [comment]
Thanks for reporting. I've fixed this issue.
